# Generated by Django 3.2 on 2021-05-07 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacto',
            old_name='cotent',
            new_name='content',
        ),
    ]
