# Generated by Django 3.2 on 2021-05-07 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_rename_cotent_contacto_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='title',
            field=models.CharField(max_length=25),
        ),
    ]
